services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
    command: uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - house_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  scraper:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    command: cron -f
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - house_network
    depends_on:
      api:
        condition: service_healthy

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command:
      - /bin/sh
      - -c
      - |
        ngrok start --all
    volumes:
      - .:/home/ngrok/.ngrok2/
    environment:
      - NGROK_AUTH_TOKEN=2hzAzrQSxoF66VanuaNc8TCv3AE_5nM4S6xDYeawNUC3HEr7a
    networks:
      - house_network
    depends_on:
      api:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - house_network
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  house_network:
    driver: bridge

volumes:
  data: 