# Generated by Django 5.1.6 on 2025-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField(max_length=500)),
                ('bedrooms', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('freguesia', models.CharField(max_length=100)),
                ('concelho', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('scraped_at', models.DateTimeField()),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('contacted', models.BooleanField(default=False)),
                ('discarded', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('house_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'houses',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
