# Generated by Django 5.0.2 on 2025-07-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField(max_length=500)),
                ('bedrooms', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('freguesia', models.CharField(max_length=100)),
                ('concelho', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('scraped_at', models.DateTimeField()),
                ('house_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'houses',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='MainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('total_houses', models.IntegerField(default=0)),
                ('new_houses', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_runs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('total_houses', models.IntegerField(default=0)),
                ('new_houses', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraper_runs',
                'ordering': ['-start_time'],
            },
        ),
    ]
