# Generated by Django 5.0.2 on 2025-07-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='contacted_by',
            field=models.ManyToManyField(blank=True, related_name='contacted_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='discarded_by',
            field=models.ManyToManyField(blank=True, related_name='discarded_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='houses.house'),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='main_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_runs', to='houses.mainrun'),
        ),
    ]
