# Generated by Django 4.2.19 on 2025-02-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='initialized', max_length=20)),
                ('houses_processed', models.IntegerField(default=0)),
                ('houses_found', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('urls_processed', models.JSONField(blank=True, null=True)),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'scraper_runs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['scraper_name', 'start_time'], name='scraper_run_scraper_a0cfaa_idx'), models.Index(fields=['status'], name='scraper_run_status_9cc131_idx')],
            },
        ),
    ]
