# Generated by Django 5.1.6 on 2025-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_scraperrun'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scraperrun',
            name='scraper_run_scraper_a0cfaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='scraperrun',
            name='scraper_run_status_9cc131_idx',
        ),
        migrations.RemoveField(
            model_name='scraperrun',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='scraperrun',
            name='success_rate',
        ),
        migrations.RemoveField(
            model_name='scraperrun',
            name='urls_processed',
        ),
        migrations.AlterField(
            model_name='scraperrun',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20),
        ),
    ]
