# Generated by Django 5.1.6 on 2025-02-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_scraperrun_scraper_run_scraper_a0cfaa_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperrun',
            old_name='houses_found',
            new_name='new_houses',
        ),
        migrations.RenameField(
            model_name='scraperrun',
            old_name='houses_processed',
            new_name='total_houses',
        ),
    ]
