# Generated by Django 5.0.2 on 2025-07-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_county_district_alter_house_concelho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='concelho',
        ),
        migrations.RemoveField(
            model_name='house',
            name='freguesia',
        ),
    ]
