# Generated by Django 5.1.6 on 2025-02-27 23:15

from django.db import migrations

def populate_scraper(apps, schema_editor):
    ScraperRun = apps.get_model('houses', 'ScraperRun')
    Scraper = apps.get_model('houses', 'Scraper')
    
    # Get all unique scraper names from House model
    House = apps.get_model('houses', 'House')
    scraper_names = House.objects.values_list('source', flat=True).distinct()
    
    # Create Scraper objects for each unique name
    scrapers = {}
    for name in scraper_names:
        scraper, _ = Scraper.objects.get_or_create(name=name)
        scrapers[name] = scraper
    
    # Update ScraperRun records
    for run in ScraperRun.objects.all():
        # Try to get the scraper from the House model
        houses = House.objects.filter(scraped_at__gte=run.start_time)
        if houses.exists():
            source = houses.first().source
            if source in scrapers:
                run.scraper = scrapers[source]
                run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_scraper_remove_scraperrun_scraper_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_scraper, reverse_code=migrations.RunPython.noop),
    ]
