# Generated by Django 4.2.19 on 2025-02-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20250227_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_houses', models.IntegerField(default=0)),
                ('new_houses', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_runs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterField(
            model_name='scraperrun',
            name='scraper',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Scraper',
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='main_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_runs', to='houses.mainrun'),
        ),
    ]
