# Generated by Django 5.1.6 on 2025-03-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_alter_scraperrun_scraper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraperrun',
            name='main_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_runs', to='houses.mainrun'),
        ),
        migrations.AlterField(
            model_name='scraperrun',
            name='scraper',
            field=models.CharField(max_length=50),
        ),
    ]
