# Generated by Django 5.0.2 on 2025-03-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_alter_house_image_urls_alter_scraperrun_main_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
