# Generated by Django 5.0.2 on 2025-03-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_link_existing_scraper_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperrun',
            name='main_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_runs', to='houses.mainrun'),
        ),
    ]
