# Generated by Django 5.0.2 on 2025-03-19 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_mainrun_execution_time_scraperrun_execution_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='house',
            name='discarded',
        ),
        migrations.RemoveField(
            model_name='house',
            name='favorite',
        ),
        migrations.AddField(
            model_name='house',
            name='contacted_by',
            field=models.ManyToManyField(blank=True, related_name='contacted_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='discarded_by',
            field=models.ManyToManyField(blank=True, related_name='discarded_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
