# Generated by Django 5.0.2 on 2025-07-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_remove_house_contacted_remove_house_discarded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image_urls',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='houses.house')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
